# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c10b7413038bfdfab89c413f66dcc1e9816b939aae918e9ef1a21e5ccd5d9be017c2c02077740719bd7b4afa765dae4d5f40683c50946b64a8edb17beda9051

test:
  secret_key_base: b80fe834c3eb11140ce192bc695b551e15725036eed13da6d7b62d65755a4f9a3c978bea70eeca0991e296320411c3d8f2379b4dc848cffe6ab0d39f7f460fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
